apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cluster-api
rules:
- apiGroups: ["", "apps"]
  resources: ["services", "statefulsets", "deployments", "pods", "configmaps"]
  verbs: ["get", "create", "update", "patch", "delete"]