apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-api
  namespace: default
subjects:
- kind: ServiceAccount
  name: cluster-api
  apiGroup: ""
roleRef:
  kind: Role
  name: cluster-api
  apiGroup: rbac.authorization.k8s.io