apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #namespace: gameservers-dev
  name: cluster-api
rules:
- apiGroups: ["", "apps", "metrics.k8s.io"]
  resources: ["services", "statefulsets", "statefulsets/scale", "deployments", "pods", "configmaps"]
  verbs: ["get", "create", "update", "patch", "delete"]