apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 50
    targetPort: primary
  type: NodePort
  #type: LoadBalancer
  #loadBalancerIP: 35.246.23.17
