apiVersion: v1
kind: Service
metadata:
  name: minecraft-id-2       # Will change
  labels:
    app: minecraft-id-2        # Will change
spec:
  type: NodePort
  #loadBalancerIP: 35.246.23.17
  #externalIPs:
  #  - "35.246.23.17"
  selector:
    app: minecraft-id-2
  ports:
  - protocol: "TCP"
    port: 25565
    targetPort: primary