apiVersion: v1
kind: Service
metadata:
  name: sftp-6
  labels:
    app: sftp-6
spec:
  type: NodePort
  #loadBalancerIP: 35.246.23.17
  #externalIPs:
  #  - "35.246.23.17"
  selector:
    app: sftp-6
  ports:
  - protocol: "TCP"
    port: 22
    targetPort: sftp-primary