apiVersion: v1
kind: Service
metadata:
  name: minecraft-id-2       # Will change
  labels:
    app: minecraft-id-2        # Will change
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 25565
  selector:
    app: minecraft-id-2        # Will change