apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft       # Will change
spec:
  selector:
    matchLabels:
      app: minecraft        # Will change
  serviceName: "minecraft"        # Will change
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft        # Will change
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: minecraft-server        # Will change
        image: eu.gcr.io/server-hosting-303517/games/minecraft-java:latest
        volumeMounts:
        - name: minecraft-data        # Will change
          mountPath: /data/server
  volumeClaimTemplates:
  - metadata:
      name: minecraft-data        # Will change
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ssd-disk"
      resources:
        requests:
          storage: 1Gi        # Will change